const usersRow = document.querySelector(".users-row");

usersRow.innerHTML = `"<div id="loading">
	
<div class="loadingio-spinner-reload-0l5t3gkdflwd"><div class="ldio-bnnng3ca4r">
<div><div></div><div></div><div></div></div>
</div></div>
</div>

<style type="text/css">
@keyframes ldio-bnnng3ca4r { 0% { transform: rotate(0) } 100% { transform: rotate(360deg); } }
.ldio-bnnng3ca4r > div {
  animation: ldio-bnnng3ca4r 1s infinite linear;
  transform-origin: 100px 100px;
}
.ldio-bnnng3ca4r > div div { position: absolute; }
.ldio-bnnng3ca4r > div div:nth-child(1), .ldio-bnnng3ca4r > div div:nth-child(2) {
  width: 164px;
  height: 164px;
  border: 24px solid;
  border-radius: 50%;
  border-color: transparent #e15b64 #e15b64 #e15b64;
  box-sizing: border-box;
  position: absolute;
  transform: rotate(45deg);
  transform-origin: 100px 100px;
}
.ldio-bnnng3ca4r > div div:nth-child(1) {
  transform: rotate(45deg) translate(18px, 18px);
}
.ldio-bnnng3ca4r > div div:nth-child(2) {
  transform: rotate(0deg) translate(18px, 18px);;
}
.ldio-bnnng3ca4r > div div:nth-child(3) {
  width: 0;
  height: 0;
  border: 24px solid;
  border-color: transparent transparent transparent #e15b64;
  transform: translate(100px, 6px);
}
.loadingio-spinner-reload-0l5t3gkdflwd {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-bnnng3ca4r {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-bnnng3ca4r div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>"`;

getData("https://jsonplaceholder.typicode.com/users", (res, status) => {
  usersRow.innerHTML = "";

  if (status === 200) {
    res.map((user) => {
      usersRow.innerHTML += `<div>
        <a  class="user" href="posts.html?userId=${user.id}">${user.id} ${user.name}</a>
      </div>`;
    });
  } else {
    usersRow.innerHTML = res;
  }
});


